as yet unclassified
initializePresenter
	firstSquare
		action: [ self putCorrespondantValueInSquare: 1.
			firstSquare label: (tateti squareNumber: 1) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	secondSquare
		action: [ self putCorrespondantValueInSquare: 2.
			secondSquare label: (tateti squareNumber: 2) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	thirdSquare
		action: [ self putCorrespondantValueInSquare: 3.
			thirdSquare label: (tateti squareNumber: 3) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	fourthSquare
		action: [ self putCorrespondantValueInSquare: 4.
			fourthSquare label: (tateti squareNumber: 4) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	fifthSquare
		action: [ self putCorrespondantValueInSquare: 5.
			fifthSquare label: (tateti squareNumber: 5) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	sixthSquare
		action: [ self putCorrespondantValueInSquare: 6.
			sixthSquare label: (tateti squareNumber: 6) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	seventhSquare
		action: [ self putCorrespondantValueInSquare: 7.
			seventhSquare label: (tateti squareNumber: 7) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	eighthSquare
		action: [ self putCorrespondantValueInSquare: 8.
			eighthSquare label: (tateti squareNumber: 8) printString.
			tateti verifyIfSomeWonOrGameEnded ].
	ninthSquare
		action: [ self putCorrespondantValueInSquare: 9.
			ninthSquare label: (tateti squareNumber: 9) printString.
			tateti verifyIfSomeWonOrGameEnded ]