as yet unclassified
initializeWidgets 
        self instantiateModels: #(
                 firstSquare     ButtonModel
					 secondSquare     ButtonModel
					 thirdSquare     ButtonModel
					 fourthSquare     ButtonModel
					 fifthSquare     ButtonModel
					 sixthSquare     ButtonModel
					 seventhSquare     ButtonModel
					 eighthSquare     ButtonModel
					 ninthSquare     ButtonModel
        ).
       self title: 'TATETI'.
       firstSquare  label:''.
		 secondSquare label:''.
		 thirdSquare  label:''.
		 fourthSquare label:''.
		 fifthSquare  label:''.
		 sixthSquare  label:''.
		 seventhSquare  label:''.
		 eighthSquare   label:''.
		 ninthSquare    label:''.